---
title: "Experience"
---

## Lethal Means Prevention Intern         (May 2026 - July 2026)

### Organization
 
Gwinnett United in Drug Education (GUIDE), Inc.

### Location(s)

Lawrenceville, GA; Waleska, GA

#### Responsibilities and Accomplishments

- Conducted research and took certification-based trainings related to Reducing Access to Lethal Means (among youths and adults) and on other topics. Findings were presented to the community (i.e., coalition boards, parents, and businesses). 

- Project included creating a booklet (with related resources) along with a presentation based on the steps and findings regarding Reducing Access to Lethal Means among youths and adults. The main topics included firearm, suffocation, and poisoning safety.  
- Utilized the Canva visual workspace platform to develop a website (https://gwinnettandsurroundingareaschri.my.canva.site/), with help from organizations in Gwinnett and surrounding areas, to provide resources related to harm reduction, mental health services, advocacy, and other categories to community members. 

